#
# Copyright IBM Corp All Rights Reserved
#
# SPDX-License-Identifier: Apache-2.0
#
version: '2'

networks:
  proofit:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.172.0.1/24

  appdb:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.172.1.0/28

  toeicdb:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.172.1.16/28

  qnetdb:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.172.1.32/28

  recruitdb:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.172.1.48/28

  smudb:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.172.1.64/28

services:
  server.ca.com:
    image: hyperledger/fabric-ca
    environment:
      - GODEBUG=netdns=go
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=server.ca.com
      - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server/ca-cert.pem
      - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server/msp/keystore/6b03deddf967a9bc02cafa30af733def8c3c69a91dd6255c10cdd87e206ee45d_sk
    working_dir: /etc/hyperledger/fabric-ca-server/
    tty: true
    ports:
      - 7054:7054
    command: sh -c 'fabric-ca-server start'
    volumes:
      - ./ca/server.ca.com/fabric-ca-server/:/etc/hyperledger/fabric-ca-server/
    container_name: server.ca.com
    networks:
      proofit:
        # ipv4_address: 172.172.0.1
        aliases:
          - server.ca.com

  admin.ca.com:
    image: hyperledger/fabric-ca
    environment:
      - GODEBUG=netdns=go
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-client
    working_dir: /etc/hyperledger/fabric-ca-client/
    tty: true
    command: /bin/bash
    volumes:
      - ./ca/admin.ca.com/fabric-ca-client/:/etc/hyperledger/fabric-ca-client/
    container_name: admin.ca.com
    networks:
      proofit:
        # ipv4_address: 172.172.0.2
        aliases:
          - admin.ca.com
    depends_on:
      - server.ca.com
     
  orderer.ca.com:
    image: hyperledger/fabric-orderer
    environment:
      - GODEBUG=netdns=go
      - FABRIC_LOGGIN_SPEC=INFO
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_LOCALMSPID=ca
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/orderer
    command: /bin/bash
    tty: true
    ports:
      - 7050:7050
    volumes:
        - ./ca/orderer.ca.com/config/:/etc/hyperledger/configtx
        - ./ca/orderer.ca.com/orderer/:/opt/gopath/src/github.com/hyperledger/fabric/orderer
    container_name: orderer.ca.com
    networks:
      proofit:
        # ipv4_address: 172.172.0.3
        aliases:
          - orderer.ca.com

  zookeeper.ca.com:
    image: hyperledger/fabric-zookeeper
    # restart: always
    ports:
      - 2181:2181
    networks:
      proofit:
        aliases:
          - zookeeper.ca.com
  
  kafka.ca.com:
    image: hyperledger/fabric-kafka
    # restart: always
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=kafka.ca.com
      - KAFKA_ADVERTISED_PORT=9092
      - KAFKA_BROKER_ID=0
      - KAFKA_MESSAGE_MAX_BYTES=103809024 # 99 * 1024 * 1024
      - KAFKA_REPLICA_FETCH_MAX_BYTES=103809024 # 99 * 1024 * 1024
      - KAFKA_NUM_REPLICA_FETCHERS=1
      - KAFKA_DEFAULT_REPLICATION_FACTOR=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper.ca.com:2181
    ports:
      - 9092:9092
    depends_on:
      - zookeeper.ca.com
    networks:
      proofit:
        aliases:
          - kafka.ca.com

  admin.app.com:
    image: hyperledger/fabric-ca
    environment:
      - GODEBUG=netdns=go
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-client
    working_dir: /etc/hyperledger/fabric-ca-client/
    tty: true
    command: /bin/bash
    volumes:
      - ./app/admin.app.com/fabric-ca-client/:/etc/hyperledger/fabric-ca-client/
    container_name: admin.app.com
    networks:
      proofit:
        # ipv4_address: 172.172.0.2
        aliases:
          - admin.app.com

  app.app.com:
    container_name: app.app.com
    image: hyperledger/fabric-peer
    environment:
      - GODEBUG=netdns=go
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: /bin/bash
    tty: true
    ports:
      - 7051:7051
      - 7052:7052
    volumes:
        - /var/run/:/host/var/run/
        - ./app/app.app.com/msp/:/etc/hyperledger/msp/
        - ./app/app.app.com/config/:/etc/hyperledger/configtx/
    depends_on:
      - orderer.ca.com
      - appdb
    networks:
      proofit:
        # ipv4_address: 172.172.0.4
        aliases:
          - app.app.com
      appdb:
        # ipv4_address: 172.172.1.1
        aliases:
          - app

  appdb:
    container_name: appdb
    image: hyperledger/fabric-couchdb
    # Populate the COUCHDB_USER and COUCHDB_PASSWORD to set an admin user and password
    # for CouchDB.  This will prevent CouchDB from operating in an "Admin Party" mode.
    environment:
      - COUCHDB_USER=appdb
      - COUCHDB_PASSWORD=appdb
    ports:
      - 5984:5984
    networks:
      appdb:
        # ipv4_address: 172.172.1.2
        aliases:
          - appdb

  recruit.app.com:
    container_name: recruit.app.com
    image: hyperledger/fabric-peer
    environment:
      - GODEBUG=netdns=go
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: /bin/bash
    tty: true
    ports:
      - 7051:7051
      - 7052:7052
    volumes:
        - /var/run/:/host/var/run/
        - ./app/recruit.app.com/msp/:/etc/hyperledger/msp/
        - ./app/recruit.app.com/config/:/etc/hyperledger/configtx/
    depends_on:
      - orderer.ca.com
      - recruitdb
    networks:
      proofit:
        # ipv4_address: 172.172.0.7
        aliases:
          - recruit.app.com
      recruitdb:
        # ipv4_address: 172.172.1.33
        aliases:
          - recruit

  recruitdb:
    container_name: recruitdb
    image: hyperledger/fabric-couchdb
    # Populate the COUCHDB_USER and COUCHDB_PASSWORD to set an admin user and password
    # for CouchDB.  This will prevent CouchDB from operating in an "Admin Party" mode.
    environment:
      - COUCHDB_USER=recruitdb
      - COUCHDB_PASSWORD=recruitdb
    ports:
      - 5984:5984
    networks:
      recruitdb:
        # ipv4_address: 172.172.1.34
        aliases:
          - recruitdb

  admin.language.com:
    image: hyperledger/fabric-ca
    environment:
      - GODEBUG=netdns=go
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-client/
    working_dir: /etc/hyperledger/fabric-ca-client/
    tty: true
    command: /bin/bash
    volumes:
      - ./language/admin.language.com/fabric-ca-client/:/etc/hyperledger/fabric-ca-client/
    container_name: admin.language.com
    networks:
      proofit:
        # ipv4_address: 172.172.0.2
        aliases:
          - admin.language.com

  toeic.language.com:
    container_name: toeic.language.com
    image: hyperledger/fabric-peer
    environment:
      - GODEBUG=netdns=go
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: /bin/bash
    tty: true
    ports:
      - 7051:7051
      - 7052:7052
    volumes:
        - /var/run/:/host/var/run/
        - ./language/toeic.language.com/msp/:/etc/hyperledger/msp/
        - ./language/toeic.language.com/config/:/etc/hyperledger/configtx/
    depends_on:
      - orderer.ca.com
      - toeicdb
    networks:
      proofit:
        # ipv4_address: 172.172.0.5
        aliases:
          - toeic.language.com
      toeicdb:
        # ipv4_address: 172.172.1.17
        aliases:
          - toeic

  toeicdb:
    container_name: toeicdb
    image: hyperledger/fabric-couchdb
    # Populate the COUCHDB_USER and COUCHDB_PASSWORD to set an admin user and password
    # for CouchDB.  This will prevent CouchDB from operating in an "Admin Party" mode.
    environment:
      - COUCHDB_USER=toeicdb
      - COUCHDB_PASSWORD=toeicdb
    ports:
      - 5984:5984
    networks:
      toeicdb:
        # ipv4_address: 172.172.1.18
        aliases:
          - toeicdb

  admin.qualify.com:
    image: hyperledger/fabric-ca
    environment:
      - GODEBUG=netdns=go
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-client
    working_dir: /etc/hyperledger/fabric-ca-client/
    tty: true
    command: /bin/bash
    volumes:
      - ./qualify/admin.qualify.com/fabric-ca-client/:/etc/hyperledger/fabric-ca-client/
    container_name: admin.qualify.com
    networks:
      proofit:
        # ipv4_address: 172.172.0.2
        aliases:
          - admin.qualify.com

  qnet.qualify.com:
    container_name: qnet.qualify.com
    image: hyperledger/fabric-peer
    environment:
      - GODEBUG=netdns=go
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: /bin/bash
    tty: true
    ports:
      - 7051:7051
      - 7052:7052
    volumes:
        - /var/run/:/host/var/run/
        - ./qualify/qnet.qualify.com/msp/:/etc/hyperledger/msp/
        - ./qualify/qnet.qualify.com/config/:/etc/hyperledger/configtx/
    depends_on:
      - orderer.ca.com
      - qnetdb
    networks:
      proofit:
        # ipv4_address: 172.172.0.6
        aliases:
          - qnet.qualify.com
      qnetdb:
        # ipv4_address: 172.172.1.33
        aliases:
          - qnet 

  qnetdb:
    container_name: qnetdb
    image: hyperledger/fabric-couchdb
    # Populate the COUCHDB_USER and COUCHDB_PASSWORD to set an admin user and password
    # for CouchDB.  This will prevent CouchDB from operating in an "Admin Party" mode.
    environment:
      - COUCHDB_USER=qnetdb
      - COUCHDB_PASSWORD=qnetdb
    ports:
      - 5984:5984
    networks:
      qnetdb:
        # ipv4_address: 172.172.1.34
        aliases:
          - qnetdb

  admin.univ.com:
    image: hyperledger/fabric-ca
    environment:
      - GODEBUG=netdns=go
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-client/
    working_dir: /etc/hyperledger/fabric-ca-client/
    tty: true
    command: /bin/bash
    volumes:
      - ./univ/admin.univ.com/fabric-ca-client/:/etc/hyperledger/fabric-ca-client/
    container_name: admin.univ.com
    networks:
      proofit:
        # ipv4_address: 172.172.0.2
        aliases:
          - admin.univ.com

  smu.univ.com:
    container_name: smu.univ.com
    image: hyperledger/fabric-peer
    environment:
      - GODEBUG=netdns=go
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: /bin/bash
    tty: true
    ports:
      - 7051:7051
      - 7052:7052
    volumes:
        - /var/run/:/host/var/run/
        - ./univ/smu.univ.com/msp/:/etc/hyperledger/msp/
        - ./univ/smu.univ.com/config/:/etc/hyperledger/configtx/
    depends_on:
      - orderer.ca.com
      - smudb
    networks:
      proofit:
        # ipv4_address: 172.172.0.8
        aliases:
          - smu.univ.com
      smudb:
        # ipv4_address: 172.172.1.65
        aliases:
          - smu

  smudb:
    container_name: smudb
    image: hyperledger/fabric-couchdb
    # Populate the COUCHDB_USER and COUCHDB_PASSWORD to set an admin user and password
    # for CouchDB.  This will prevent CouchDB from operating in an "Admin Party" mode.
    environment:
      - COUCHDB_USER=smudb
      - COUCHDB_PASSWORD=smudb
    ports:
      - 5984:5984
    networks:
      smudb:
        # ipv4_address: 172.172.1.66
        aliases:
          - smudb
