#
# Copyright IBM Corp All Rights Reserved
#
# SPDX-License-Identifier: Apache-2.0
#
version: '2'

networks:
  proofit:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.172.0.1/20

services:
  server.ca.com:
    image: hyperledger/fabric-ca:1.4.1
    environment:
      - GODEBUG=netdns=go
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server/
    working_dir: /etc/hyperledger/fabric-ca-server/
    tty: true
    ports:
      - 7054:7054
    command: fabric-ca-server start
    volumes:
      - ./ca/server.ca.com/fabric-ca-server/:/etc/hyperledger/fabric-ca-server/
    container_name: server.ca.com
    networks:
      proofit:
        aliases:
          - server.ca.com

  admin.ca.com:
    image: hyperledger/fabric-ca:1.4.1
    environment:
      - GODEBUG=netdns=go
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-client/
    working_dir: /etc/hyperledger/fabric-ca-client/
    tty: true
    command: /bin/bash
    volumes:
      - ./ca/admin.ca.com/fabric-ca-client/:/etc/hyperledger/fabric-ca-client/
    container_name: admin.ca.com
    networks:
      proofit:
        aliases:
          - admin.ca.com
    depends_on:
      - server.ca.com
     
  orderer.ca.com:
    image: hyperledger/fabric-orderer:1.4.1    
    environment:
      - GODEBUG=netdns=go
        # - FABRIC_LOGGING_SPEC=DEBUG
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_LOGLEVEL=debug
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/
    command: orderer
    tty: true
    ports:
      - 7050:7050
    volumes:
        - ./ca/orderer.ca.com/working_dir/:/opt/gopath/src/github.com/hyperledger/fabric/
        - ./ca/orderer.ca.com/production/:/var/hyperledger/production/orderer/
        - ./ca/orderer.ca.com/etc/:/etc/hyperledger/fabric/
        - ./y_binaries/:/usr/local/bin/
    container_name: orderer.ca.com
    networks:
      proofit:
        aliases:
          - orderer.ca.com
    depends_on:
      - server.ca.com
      - kafka.ca.com
      - zookeeper.ca.com

  zookeeper.ca.com:
    image: hyperledger/fabric-zookeeper
    container_name: zookeeper.ca.com
    # restart: always
    ports:
      - 2181:2181
    networks:
      proofit:
        aliases:
          - zookeeper.ca.com
  
  kafka.ca.com:
    image: hyperledger/fabric-kafka
    # restart: always
    container_name: kafka.ca.com
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=kafka.ca.com
      - KAFKA_ADVERTISED_PORT=9092
      - KAFKA_BROKER_ID=0
      - KAFKA_MESSAGE_MAX_BYTES=77777777  # 103809024 # 99 * 1024 * 1024
      - KAFKA_REPLICA_FETCH_MAX_BYTES=77777777 # 103809024 # 99 * 1024 * 1024
      - KAFKA_NUM_REPLICA_FETCHERS=1
      - KAFKA_DEFAULT_REPLICATION_FACTOR=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper.ca.com:2181
    ports:
      - 9092:9092
    depends_on:
      - zookeeper.ca.com
    networks:
      proofit:
        aliases:
          - kafka.ca.com

  admin.app.com:
    image: hyperledger/fabric-ca:1.4.1 
    environment:
      - GODEBUG=netdns=go
        #- FABRIC_LOGGING_SPEC=grpc=debug:debug
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-client/
      - FABRIC_CFG_PATH=/etc/hyperledger/fabric-ca-client/
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=proofit_proofit
    working_dir: /etc/hyperledger/fabric-ca-client/
    tty: true
    command: peer node start
    ports:
      - 7151:7151
      - 7152:7152
    volumes:
      - /var/run/:/host/var/run/
      - ./app/admin.app.com/fabric-ca-client/:/etc/hyperledger/fabric-ca-client/
      - ./app/admin.app.com/production/:/var/hyperledger/production/
      - ./y_binaries/:/usr/local/bin/
      - ./y_chaincode/:/etc/hyperledger/chaincode/
    container_name: admin.app.com
    networks:
      proofit:
        aliases:
          - admin.app.com

  app.app.com:
    container_name: app.app.com
    image: hyperledger/fabric-peer:1.4.1 
    environment:
      - GODEBUG=netdns=go
      - FABRIC_LOGGING_SPEC=grpc=debug:debug
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=proofit_proofit
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/
    command: peer node start
    tty: true
    ports:
      - 7051:7051
      - 7052:7052
    volumes:
        - /var/run/:/host/var/run/
        - ./app/app.app.com/working_dir/:/opt/gopath/src/github.com/hyperledger/fabric/
        - ./app/app.app.com/etc/:/etc/hyperledger/fabric/
        - ./app/app.app.com/production/:/var/hyperledger/production/
        - ./y_binaries/:/usr/local/bin/
    depends_on:
      - orderer.ca.com
      - appdb
    networks:
      proofit:
        aliases:
          - app.app.com

  appdb:
    container_name: appdb
    image: hyperledger/fabric-couchdb:0.4.15
    # Populate the COUCHDB_USER and COUCHDB_PASSWORD to set an admin user and password
    # for CouchDB.  This will prevent CouchDB from operating in an "Admin Party" mode.
    environment:
      - COUCHDB_USER=appdb
      - COUCHDB_PASSWORD=appdb
    ports:
      - 7984:5984
    networks:
      proofit:
        aliases:
          - appdb


  admin.recruit.com:
    image: hyperledger/fabric-ca:1.4.1 
    environment:
      - GODEBUG=netdns=go
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-client/
      - FABRIC_CFG_PATH=/etc/hyperledger/fabric-ca-client/
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=proofit_proofit
    working_dir: /etc/hyperledger/fabric-ca-client/
    tty: true
    command: peer node start
    ports:
      - 8151:8151
      - 8152:8152
    volumes:
      - /var/run/:/host/var/run/
      - ./recruit/admin.recruit.com/fabric-ca-client/:/etc/hyperledger/fabric-ca-client/
      - ./recruit/admin.recruit.com/production/:/var/hyperledger/production/
      - ./y_binaries/:/usr/local/bin/
      - ./y_chaincode/:/etc/hyperledger/chaincode/
    container_name: admin.recruit.com
    networks:
      proofit:
        aliases:
          - admin.recruit.com

  sk.recruit.com:
    container_name: sk.recruit.com
    image: hyperledger/fabric-peer:1.4.1 
    environment:
      - GODEBUG=netdns=go
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=proofit_proofit
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/
    command: peer node start
    tty: true
    ports:
      - 8051:8051
      - 8052:8052
    volumes:
        - /var/run/:/host/var/run/
        - ./recruit/sk.recruit.com/working_dir/:/opt/gopath/src/github.com/hyperledger/fabric/
        - ./recruit/sk.recruit.com/etc/:/etc/hyperledger/fabric/
        - ./recruit/sk.recruit.com/production/:/var/hyperledger/production/
        - ./y_binaries/:/usr/local/bin/
    depends_on:
      - orderer.ca.com
      - skdb
    networks:
      proofit:
        aliases:
          - sk.recruit.com

  skdb:
    container_name: skdb
    image: hyperledger/fabric-couchdb:0.4.15
    # Populate the COUCHDB_USER and COUCHDB_PASSWORD to set an admin user and password
    # for CouchDB.  This will prevent CouchDB from operating in an "Admin Party" mode.
    environment:
      - COUCHDB_USER=skdb
      - COUCHDB_PASSWORD=skdb
    ports:
      - 8984:5984
    networks:
      proofit:
        aliases:
          - skdb

  admin.univ.com:
    image: hyperledger/fabric-ca:1.4.1 
    environment:
      - GODEBUG=netdns=go
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-client/
      - FABRIC_CFG_PATH=/etc/hyperledger/fabric-ca-client/
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=proofit_proofit
    working_dir: /etc/hyperledger/fabric-ca-client/
    tty: true
    command: peer node start
    ports:
      - 9151:9151
      - 9152:9152
    volumes:
      - /var/run/:/host/var/run/
      - ./univ/admin.univ.com/fabric-ca-client/:/etc/hyperledger/fabric-ca-client/
      - ./univ/admin.univ.com/production/:/var/hyperledger/production/
      - ./y_binaries/:/usr/local/bin/
      - ./y_chaincode/:/etc/hyperledger/chaincode/
    container_name: admin.univ.com
    networks:
      proofit:
        aliases:
          - admin.univ.com

  dku.univ.com:
    container_name: dku.univ.com
    image: hyperledger/fabric-peer:1.4.1 
    environment:
      - GODEBUG=netdns=go
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=proofit_proofit
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/
    command: peer node start
    tty: true
    ports:
      - 9061:9061
      - 9062:9062
    volumes:
        - /var/run/:/host/var/run/
        - ./univ/dku.univ.com/working_dir/:/opt/gopath/src/github.com/hyperledger/fabric/
        - ./univ/dku.univ.com/etc/:/etc/hyperledger/fabric/
        - ./univ/dku.univ.com/production/:/var/hyperledger/production/
        - ./y_binaries/:/usr/local/bin/
    depends_on:
      - orderer.ca.com
      - dkudb
    networks:
      proofit:
        aliases:
          - dku.univ.com

  dkudb:
    container_name: dkudb
    image: hyperledger/fabric-couchdb:0.4.15
    # Populate the COUCHDB_USER and COUCHDB_PASSWORD to set an admin user and password
    # for CouchDB.  This will prevent CouchDB from operating in an "Admin Party" mode.
    environment:
      - COUCHDB_USER=dkudb
      - COUCHDB_PASSWORD=dkudb
    ports:
      - 9884:5984
    networks:
      proofit:
        aliases:
          - dkudb

  smu.univ.com:
    container_name: smu.univ.com
    image: hyperledger/fabric-peer:1.4.1 
    environment:
      - GODEBUG=netdns=go
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
        #- FABRIC_LOGGING_SPEC=grpc=debug:debug
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=proofit_proofit
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/
    command: peer node start
    tty: true
    ports:
      - 9051:9051
      - 9052:9052
    volumes:
        - /var/run/:/host/var/run/
        - ./univ/smu.univ.com/working_dir/:/opt/gopath/src/github.com/hyperledger/fabric/
        - ./univ/smu.univ.com/etc/:/etc/hyperledger/fabric/
        - ./univ/smu.univ.com/production/:/var/hyperledger/production/
        - ./y_binaries/:/usr/local/bin/
    depends_on:
      - orderer.ca.com
      - smudb
    networks:
      proofit:
        aliases:
          - smu.univ.com

  smudb:
    container_name: smudb
    image: hyperledger/fabric-couchdb:0.4.15
    # Populate the COUCHDB_USER and COUCHDB_PASSWORD to set an admin user and password
    # for CouchDB.  This will prevent CouchDB from operating in an "Admin Party" mode.
    environment:
      - COUCHDB_USER=smudb
      - COUCHDB_PASSWORD=smudb
    ports:
      - 9984:5984
    networks:
      proofit:
        aliases:
          - smudb

  admin.license.com:
    image: hyperledger/fabric-ca:1.4.1 
    environment:
      - GODEBUG=netdns=go
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-client/
      - FABRIC_CFG_PATH=/etc/hyperledger/fabric-ca-client/
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=proofit_proofit
    working_dir: /etc/hyperledger/fabric-ca-client/
    tty: true
    command: peer node start
    ports:
      - 10151:10151
      - 10152:10152
    volumes:
      - /var/run/:/host/var/run/
      - ./license/admin.license.com/fabric-ca-client/:/etc/hyperledger/fabric-ca-client/
      - ./license/admin.license.com/production/:/var/hyperledger/production/
      - ./y_binaries/:/usr/local/bin/
      - ./y_chaincode/:/etc/hyperledger/chaincode/
    container_name: admin.license.com
    networks:
      proofit:
        aliases:
          - admin.license.com

  qnet.license.com:
    container_name: qnet.license.com
    image: hyperledger/fabric-peer:1.4.1 
    environment:
      - GODEBUG=netdns=go
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=proofit_proofit
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/
    command: peer node start
    tty: true
    ports:
      - 10051:10051
      - 10052:10052
    volumes:
        - /var/run/:/host/var/run/
        - ./license/qnet.license.com/working_dir/:/opt/gopath/src/github.com/hyperledger/fabric/
        - ./license/qnet.license.com/etc/:/etc/hyperledger/fabric/
        - ./license/qnet.license.com/production/:/var/hyperledger/production/
        - ./y_binaries/:/usr/local/bin/
    depends_on:
      - orderer.ca.com
      - qnetdb
    networks:
      proofit:
        aliases:
          - qnet.license.com

  qnetdb:
    container_name: qnetdb
    image: hyperledger/fabric-couchdb:0.4.15
    # Populate the COUCHDB_USER and COUCHDB_PASSWORD to set an admin user and password
    # for CouchDB.  This will prevent CouchDB from operating in an "Admin Party" mode.
    environment:
      - COUCHDB_USER=qnetdb
      - COUCHDB_PASSWORD=qnetdb
    ports:
      - 10984:5984
    networks:
      proofit:
        aliases:
          - qnetdb


  admin.language.com:
    image: hyperledger/fabric-ca:1.4.1 
    environment:
      - GODEBUG=netdns=go
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-client/
      - FABRIC_CFG_PATH=/etc/hyperledger/fabric-ca-client/
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=proofit_proofit
    working_dir: /etc/hyperledger/fabric-ca-client/
    tty: true
    command: peer node start
    ports:
      - 11151:11151
      - 11152:11152
    volumes:
      - /var/run/:/host/var/run/
      - ./language/admin.language.com/fabric-ca-client/:/etc/hyperledger/fabric-ca-client/
      - ./language/admin.language.com/production/:/var/hyperledger/production/
      - ./y_binaries/:/usr/local/bin/
      - ./y_chaincode/:/etc/hyperledger/chaincode/
    container_name: admin.language.com
    networks:
      proofit:
        aliases:
          - admin.language.com

  toeic.language.com:
    container_name: toeic.language.com
    image: hyperledger/fabric-peer:1.4.1 
    environment:
      - GODEBUG=netdns=go
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=proofit_proofit
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/
    command: peer node start
    tty: true
    ports:
      - 11051:11051
      - 11052:11052
    volumes:
        - /var/run/:/host/var/run/
        - ./language/toeic.language.com/working_dir/:/opt/gopath/src/github.com/hyperledger/fabric/
        - ./language/toeic.language.com/etc/:/etc/hyperledger/fabric/
        - ./language/toeic.language.com/production/:/var/hyperledger/production/
        - ./y_binaries/:/usr/local/bin/
    depends_on:
      - orderer.ca.com
      - toeicdb
    networks:
      proofit:
        aliases:
          - toeic.language.com

  toeicdb:
    container_name: toeicdb
    image: hyperledger/fabric-couchdb:0.4.15 
    # Populate the COUCHDB_USER and COUCHDB_PASSWORD to set an admin user and password
    # for CouchDB.  This will prevent CouchDB from operating in an "Admin Party" mode.
    environment:
      - COUCHDB_USER=toeicdb
      - COUCHDB_PASSWORD=toeicdb
    ports:
      - 11984:5984
    networks:
      proofit:
        aliases:
          - toeicdb
