#
# Copyright IBM Corp All Rights Reserved
#
# SPDX-License-Identifier: Apache-2.0
#
version: '2'

networks:
  proofit:
    driver: bridge
      driver_opts:
        com.docker.network.enable_ipv6: "false"
      ipam:
        driver: default
        config:
        - subnet: 172.172.0.1/24

  appdb:
    driver: bridge
    iapm:
      driver: default
      config:
      - subnet: 172.172.1.0/28
{
  # languagedb:
  #   driver: bridge
  #   iapm:
  #     driver: default
  #     config:
  #     - subnet: 172.172.1.16/28

  # qualifydb:
  #   driver: bridge
  #   iapm:
  #     driver: default
  #     config:
  #     - subnet: 172.172.1.32/28
}
  recruitdb:
    driver: bridge
    iapm:
      driver: default
      config:
      - subnet: 172.172.1.48/28

  univdb:
    driver: bridge
    iapm:
      driver: default
      config:
      - subnet: 172.172.1.64/28

services:
  server.ca.com:
    image: nawhes/fabric-ca-server:1
    environment:
      - GODEBUG=netdns=go
    tty: true
    ports:
      - 7054:7054
    volumes:
      - ./crypto-config/ca/:/crypto-config/ca/
    container_name: server.ca.com
    networks:
      proofit:
        # ipv4_address: 172.172.0.1
        aliases:
          - server.ca.com

  client.ca.com:
    image: nawhes/fabric-orderer:1
    environment:
      - GODEBUG=netdns=go
    tty: true
    volumes:
      - ./crypto-config/ca/client/:/crypto-config/ca/client/
    container_name: client.ca.com
    networks:
      proofit:
        # ipv4_address: 172.172.0.2
        aliases:
          - client.ca.com
    depends_on:
      - server.ca.com
     
  orderer.ca.com:
    image: nawhes/fabric-orderer:1
    environment:
      - GODEBUG=netdns=go
      - FABRIC_LOGGIN_SPEC=INFO
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_LOCALMSPID=ca
    tty: true
    ports:
      - 7050:7050
    volumes:
        - ./crypto-config/ca/orderer/config/:/crypto-config/ca/orderer/config/
        - ./crypto-config/ca/orderer/:/crypto-config/ca/orderer/
    container_name: orderer.ca.com
      proofit:
        # ipv4_address: 172.172.0.3
        aliases:
          - orderer.ca.com

  app.app.com:
    container_name: app.app.com
    image: nawhes/fabric-peer:1
    environment:
      - GODEBUG=netdns=go
      - CORE_PEER_ID=app.app.com
      - CORE_PEER_ADDRESS=app.app.com:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_CHAINCODEADDRESS=app.app.com:7052
      - CORE_PEER_CAHINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=app.app.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=language.app.com:751
      - CORE_PEER_LICALMSPID=app
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=appdb:5984
      # The CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME and CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD
      # provide the credentials for ledger to connect to CouchDB.  The username and password must
      # match the username and password set for the associated CouchDB.
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=appdb
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=appdb
    tty: true
    ports:
      - 7051:7051
      - 7052:7052
    volumes:
        - ./crypto-config/peerOrganizations/app:/crypto-config/peerOrganizations/app
        - ./crypto-config/peerOrganizations/app/config/:/crypto-config/peerOrganizations/app/config/
    depends_on:
      - orderer.ca.com
      - appdb
    networks:
      proofit:
        # ipv4_address: 172.172.0.4
        aliases:
          - app.app.com
      appdb:
        # ipv4_address: 172.172.1.1
        aliases:
          - app

  appdb:
    container_name: appdb
    image: hyperledger/fabric-couchdb
    # Populate the COUCHDB_USER and COUCHDB_PASSWORD to set an admin user and password
    # for CouchDB.  This will prevent CouchDB from operating in an "Admin Party" mode.
    environment:
      - COUCHDB_USER=appdb
      - COUCHDB_PASSWORD=appdb
    ports:
      - 5984:5984
    networks:
      appdb:
        # ipv4_address: 172.172.1.2
        aliases:
          - appdb
{
  # language.language.com:
  #   container_name: language.language.com
  #   image: nawhes/fabric-peer:1
  #   environment: 
  #     - GODEBUG=netdns=go 
  #     - CORE_PEER_ID=language.language.com
  #     - CORE_PEER_ADDRESS=language.language.com:7051
  #     - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
  #     - CORE_PEER_CHAINCODEADDRESS=language.language.com:7052
  #     - CORE_PEER_CAHINCODELISTENADDRESS=0.0.0.0:7052
  #     - CORE_PEER_GOSSIP_EXTERNALENDPOINT=language.language.com:7051
  #     - CORE_PEER_GOSSIP_BOOTSTRAP=app.app.com:7051
  #     - CORE_PEER_LICALMSPID=language
  #     - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
  #     - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=languagedb:5984
  #     # The CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME and CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD
  #     # provide the credentials for ledger to connect to CouchDB.  The username and password must
  #     # match the username and password set for the associated CouchDB.
  #     - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=languagedb
  #     - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=languagedb
  #   tty: true
  #   ports:
  #     - 7051:7051
  #     - 7052:7052
  #   volumes:
  #       - ./crypto-config/peerOrganizations/language/:/crypto-config/peerOrganizations/language/
  #       - ./crypto-config/peerOrganizations/language/config/:/crypto-config/peerOrganizations/language/config/
  #   depends_on:
  #     - orderer.ca.com
  #     - language
  #   networks:
  #     proofit:
  #       # ipv4_address: 172.172.0.5
  #       aliases:
  #         - language.language.com
  #     languagedb:
  #       # ipv4_address: 172.172.1.17
  #       aliases:
  #         - language

  # languagedb:
  #   container_name: languagedb
  #   image: hyperledger/fabric-couchdb
  #   # Populate the COUCHDB_USER and COUCHDB_PASSWORD to set an admin user and password
  #   # for CouchDB.  This will prevent CouchDB from operating in an "Admin Party" mode.
  #   environment:
  #     - COUCHDB_USER=languagedb
  #     - COUCHDB_PASSWORD=languagedb
  #   ports:
  #     - 5984:5984
  #   networks:
  #     languagedb:
  #       # ipv4_address: 172.172.1.18
  #       aliases:
  #         - langaugedb
}
{
  # qualify.qualify.com:
  #   container_name: qualify.qualify.com
  #   image: nawhes/fabric-peer:1
  #   environment: 
  #     - GODEBUG=netdns=go
  #     - CORE_PEER_ID=qualify.qualify.com
  #     - CORE_PEER_ADDRESS=qualify.qualify.com:7051
  #     - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
  #     - CORE_PEER_CHAINCODEADDRESS=qualify.qualify.com:7052
  #     - CORE_PEER_CAHINCODELISTENADDRESS=0.0.0.0:7052
  #     - CORE_PEER_GOSSIP_EXTERNALENDPOINT=qualify.qualify.com:7051
  #     - CORE_PEER_GOSSIP_BOOTSTRAP=app.app.com:7051
  #     - CORE_PEER_LICALMSPID=qualify
  #     - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
  #     - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=qualifydb:5984
  #     # The CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME and CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD
  #     # provide the credentials for ledger to connect to CouchDB.  The username and password must
  #     # match the username and password set for the associated CouchDB.
  #     - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=qualifydb
  #     - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=qualifydb
  #   tty: true
  #   ports:
  #     - 7051:7051
  #     - 7052:7052
  #   volumes:
  #       - ./crypto-config/peerOrganizations/qualify/:/crypto-config/peerOrganizations/qualify/
  #       - ./crypto-config/peerOrganizations/qualify/config/:/crypto-config/peerOrganizations/qualify/config/
  #   depends_on:
  #     - orderer.ca.com
  #     - qualify
  #   networks:
  #     proofit:
  #       # ipv4_address: 172.172.0.6
  #       aliases:
  #         - qualify.qualify.com
  #     qualifydb:
  #       # ipv4_address: 172.172.1.33
  #       aliases:
  #         - qualify 

  # qualifydb:
  #   container_name: qualifydb
  #   image: hyperledger/fabric-couchdb
  #   # Populate the COUCHDB_USER and COUCHDB_PASSWORD to set an admin user and password
  #   # for CouchDB.  This will prevent CouchDB from operating in an "Admin Party" mode.
  #   environment:
  #     - COUCHDB_USER=qualifydb
  #     - COUCHDB_PASSWORD=qualifydb
  #   ports:
  #     - 5984:5984
  #   networks:
  #     qualifydb:
  #       # ipv4_address: 172.172.1.34
  #       aliases:
  #         - qualifydb
}
  recruit.recruit.com:
    container_name: recruit.recruit.com
    image: nawhes/fabric-peer:1
    environment:
      - GODEBUG=netdns=go
      - CORE_PEER_ID=recruit.recruit.com
      - CORE_PEER_ADDRESS=recruit.recruit.com:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_CHAINCODEADDRESS=language.language.com:7052
      - CORE_PEER_CAHINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=language.language.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=app.app.com:7051
      - CORE_PEER_LICALMSPID=recruit
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=recruitdb:5984
      # The CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME and CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD
      # provide the credentials for ledger to connect to CouchDB.  The username and password must
      # match the username and password set for the associated CouchDB.
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=recruitdb
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=recruitdb
    tty: true
    ports:
      - 7051:7051
      - 7052:7052
    volumes:
       - ./crypto-config/peerOrganizations/recruit/:/crypto-config/peerOrganizations/recruit/
       - ./crypto-config/peerOrganizations/recruit/config/:/crypto-config/peerOrganizations/recruit/config/
    depends_on:
      - orderer.ca.com
      - recruitdb
    networks:
      proofit:
        # ipv4_address: 172.172.0.7
        aliases:
          - recruit.recruit.com
      recruitdb:
        # ipv4_address: 172.172.1.33
        aliases:
          - recruit

  recruitdb:
    container_name: recruitdb
    image: hyperledger/fabric-couchdb
    # Populate the COUCHDB_USER and COUCHDB_PASSWORD to set an admin user and password
    # for CouchDB.  This will prevent CouchDB from operating in an "Admin Party" mode.
    environment:
      - COUCHDB_USER=recruitdb
      - COUCHDB_PASSWORD=recruitdb
    ports:
      - 5984:5984
    networks:
      recruitdb:
        # ipv4_address: 172.172.1.34
       aliases:
         - recruitdb

  univ.univ.com:
    container_name: univ.univ.com
    image: nawhes/fabric-peer:1
    environment:
      - GODEBUG=netdns=go
      - CORE_PEER_ID=univ.univ.com
      - CORE_PEER_ADDRESS=univ.univ.com:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_CHAINCODEADDRESS=language.language.com:7052
      - CORE_PEER_CAHINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=language.language.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=app.app.com:7051
      - CORE_PEER_LICALMSPID=univ
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=univdb:5984
      # The CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME and CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD
      # provide the credentials for ledger to connect to CouchDB.  The username and password must
      # match the username and password set for the associated CouchDB.
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=univdb
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=univdb
    tty: true
    ports:
      - 7051:7051
      - 7052:7052
    volumes:
       - ./crypto-config/peerOrganizations/univ/:/crypto-config/peerOrganizations/univ/
       - ./crypto-config/peerOrganizations/univ/config/:/crypto-config/peerOrganizations/univ/config/
    depends_on:
      - orderer.ca.com
      - univdb
    networks:
      proofit:
        # ipv4_address: 172.172.0.8
        aliases:
          - univ.univ.com
      univdb:
        # ipv4_address: 172.172.1.65
        aliases:
          - univ

  univdb:
    container_name: univdb
    image: hyperledger/fabric-couchdb
    # Populate the COUCHDB_USER and COUCHDB_PASSWORD to set an admin user and password
    # for CouchDB.  This will prevent CouchDB from operating in an "Admin Party" mode.
    environment:
      - COUCHDB_USER=univdb
      - COUCHDB_PASSWORD=univdb
    ports:
      - 5984:5984
    networks:
      univdb:
        # ipv4_address: 172.172.1.66
        aliases:
          - univdb