#
# Copyright IBM Corp All Rights Reserved
#
# SPDX-License-Identifier: Apache-2.0
#
version: '2'

networks:
  pheromone:

services:
  server.ca.com:
    image: nawhes/fabric-ca-server:1
    environment:
      - GODEBUG=netdns=go
    tty: true
    ports:
      - 7054:7054
    volumes:
      - ./ca/server/:/fabric/
    container_name: server.ca.com
    networks:
      - pheromone

  client.ca.com:
    image: nawhes/fabric-orderer:1
    environment:
      - GODEBUG=netdns=go
    tty: true
    volumes:
      - ./ca/client/:/fabric/
    container_name: client.ca.com
    networks:
      - pheromone
    depends_on:
      - server.ca.com
     
  orderer.ca.com:
    image: nawhes/fabric-orderer:1
    environment:
      - GODEBUG=netdns=go
      - FABRIC_LOGGIN_SPEC=INFO
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_LOCALMSPID=ca
    tty: true
    ports:
      - 7050:7050
    volumes:
        - ./ca/orderer/config/:/config/
        - ./ca/orderer/:/fabric/
    container_name: orderer.ca.com
    networks:
      - pheromone

  app.app.com:
    container_name: app.app.com
    image: nawhes/fabric-peer:1
    environment:
      - GODEBUG=netdns=go
      - CORE_PEER_ID=app.app.com
      - CORE_PEER_ADDRESS=app.app.com:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_CHAINCODEADDRESS=app.app.com:7052
      - CORE_PEER_CAHINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=app.app.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=academy.app.com:8051
      - CORE_PEER_LICALMSPID=app
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=appcouchdb.app.com:5984
      # The CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME and CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD
      # provide the credentials for ledger to connect to CouchDB.  The username and password must
      # match the username and password set for the associated CouchDB.
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=appcouchdb.app.com
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=appcouchdb
    tty: true
    ports:
      - 7051:7051
      - 7052:7052
    volumes:
        - ./app/app/:/fabric/
        - ./app/app/config/:/config/
    depends_on:
      - orderer.ca.com
      - appcouchdb.app.com
    networks:
      - pheromone

  appcouchdb.app.com:
    container_name: appcouchdb.app.com
    image: hyperledger/fabric-couchdb
    # Populate the COUCHDB_USER and COUCHDB_PASSWORD to set an admin user and password
    # for CouchDB.  This will prevent CouchDB from operating in an "Admin Party" mode.
    environment:
      - COUCHDB_USER=appcouchdb.app.com
      - COUCHDB_PASSWORD=appcouchdb
    ports:
      - 6984:5984
    networks:
      - pheromone

  academy.app.com:
    container_name: academy.app.com
    image: nawhes/fabric-peer:1
    environment:
      - GODEBUG=netdns=go
      - CORE_PEER_ID=academy.app.com
      - CORE_PEER_ADDRESS=academy.app.com:8051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:8051
      - CORE_PEER_CHAINCODEADDRESS=academy.app.com:8052
      - CORE_PEER_CAHINCODELISTENADDRESS=0.0.0.0:8052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=academy.app.com:8051
      - CORE_PEER_GOSSIP_BOOTSTRAP=hiring.app.com:9051
      - CORE_PEER_LICALMSPID=app
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=academycouchdb.app.com:5984
     # The CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME and CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD
     # provide the credentials for ledger to connect to CouchDB.  The username and password must
     # match the username and password set for the associated CouchDB.
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=academycouchdb.app.com
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=academycouchdb
    tty: true
    ports:
      - 8051:8051
      - 8052:8052
    volumes:
        - ./app/academy/:/fabric/
        - ./app/academy/config/:/config/
    depends_on:
      - orderer.ca.com
      - academycouchdb.app.com
    networks:
      - pheromone

  academycouchdb.app.com:
    container_name: academycouchdb.app.com
    image: hyperledger/fabric-couchdb
    # Populate the COUCHDB_USER and COUCHDB_PASSWORD to set an admin user and password
    # for CouchDB.  This will prevent CouchDB from operating in an "Admin Party" mode.
    environment:
      - GODEBUG=netdns=go
      - COUCHDB_USER=academycouchdb.app.com
      - COUCHDB_PASSWORD=academycouchdb
    ports:
      - 7984:5984
    networks:
      - pheromone
           
  hiring.app.com:
    container_name: hiring.app.com
    image: nawhes/fabric-peer:1
    environment:
      - GODEBUG=netdns=go
      - CORE_PEER_ID=hiring.app.com
      - CORE_PEER_ADDRESS=hiring.app.com:9051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:9051
      - CORE_PEER_CHAINCODEADDRESS=hiring.app.com:9052
      - CORE_PEER_CAHINCODELISTENADDRESS=0.0.0.0:9052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=hiring.app.com:9051
      - CORE_PEER_GOSSIP_BOOTSTRAP=app.app.com:7051
      - CORE_PEER_LICALMSPID=app
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=hiringcouchdb.app.com:5984
      # The CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME and CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD
      # provide the credentials for ledger to connect to CouchDB.  The username and password must
      # match the username and password set for the associated CouchDB.
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=hiringcouchdb.app.com
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=hiringcouchdb
    tty: true
    ports:
      - 9051:9051
      - 9052:9052
    volumes:
       - ./app/hiring/:/fabric/
       - ./app/hiring/config/:/config/
    depends_on:
      - orderer.ca.com
      - hiringcouchdb.app.com
    networks:
      - pheromone

  hiringcouchdb.app.com:
    container_name: hiringcouchdb.app.com
    image: hyperledger/fabric-couchdb
    # Populate the COUCHDB_USER and COUCHDB_PASSWORD to set an admin user and password
    # for CouchDB.  This will prevent CouchDB from operating in an "Admin Party" mode.
    environment:
      - COUCHDB_USER=hiringcouchdb.app.com
      - COUCHDB_PASSWORD=hiringcouchdb
    ports:
      - 8984:5984
    networks:
      - pheromone
 
  app.hiring.com:
    container_name: app.hiring.com
    image: nawhes/fabric-peer:1
    environment:
      - GODEBUG=netdns=go
      - CORE_PEER_ID=app.hiring.com
      - CORE_PEER_ADDRESS=app.hiring.com:10051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:10051
      - CORE_PEER_CHAINCODEADDRESS=app.hiring.com:10052
      - CORE_PEER_CAHINCODELISTENADDRESS=0.0.0.0:10052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=app.hiring.com:10051
      - CORE_PEER_GOSSIP_BOOTSTRAP=academy.hiring.com:11051
      - CORE_PEER_LICALMSPID=hiring
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=appcouchdb.hiring.com:5984
      # The CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME and CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD
      # provide the credentials for ledger to connect to CouchDB.  The username and password must
      # match the username and password set for the associated CouchDB.
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=appcouchdb.hiring.com
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=appcouchdb
    tty: true
    ports:
      - 10051:10051
      - 10052:10052
    volumes:
       - ./hiring/app/:/fabric/
       - ./hiring/app/config/:/config/
    depends_on:
      - orderer.ca.com
      - appcouchdb.hiring.com
    networks:
      - pheromone

  appcouchdb.hiring.com:
    container_name: appcouchdb.hiring.com
    image: hyperledger/fabric-couchdb
    # Populate the COUCHDB_USER and COUCHDB_PASSWORD to set an admin user and password
    # for CouchDB.  This will prevent CouchDB from operating in an "Admin Party" mode.
    environment:
      - COUCHDB_USER=appcouchdb.hiring.com
      - COUCHDB_PASSWORD=appcouchdb
    ports:
      - 9984:5984
    networks:
      - pheromone

  academy.hiring.com:
    container_name: academy.hiring.com
    image: nawhes/fabric-peer:1
    environment:
      - GODEBUG=netdns=go
      - CORE_PEER_ID=academy.hiring.com
      - CORE_PEER_ADDRESS=academy.hiring.com:11051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:11051
      - CORE_PEER_CHAINCODEADDRESS=academy.hiring.com:11052
      - CORE_PEER_CAHINCODELISTENADDRESS=0.0.0.0:11052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=academy.hiring.com:11051
      - CORE_PEER_GOSSIP_BOOTSTRAP=hiring.hiring.com:12051
      - CORE_PEER_LICALMSPID=hiring
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=academycouchdb.hiring.com:5984
      # The CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME and CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD
      # provide the credentials for ledger to connect to CouchDB.  The username and password must
      # match the username and password set for the associated CouchDB.
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=academycouchdb.hiring.com
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=academycouchdb
    tty: true
    ports:
      - 11051:11051
      - 11052:11052
    volumes:
       - ./hiring/academy/:/fabric/
       - ./hiring/academy/config/:/config/
    depends_on:
      - orderer.ca.com
      - academycouchdb.hiring.com
    networks:
      - pheromone

  academycouchdb.hiring.com:
    container_name: academycouchdb.hiring.com
    image: hyperledger/fabric-couchdb
    # Populate the COUCHDB_USER and COUCHDB_PASSWORD to set an admin user and password
    # for CouchDB.  This will prevent CouchDB from operating in an "Admin Party" mode.
    environment:
      - COUCHDB_USER=academycouchdb.hiring.com
      - COUCHDB_PASSWORD=academycouchdb
    ports:
      - 10984:5984
    networks:
      - pheromone
 
  hiring.hiring.com:
    container_name: hiring.hiring.com
    image: nawhes/fabric-peer:1
    environment:
      - GODEBUG=netdns=go
      - CORE_PEER_ID=hiring.hiring.com
      - CORE_PEER_ADDRESS=hiring.hiring.com:12051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:12051
      - CORE_PEER_CHAINCODEADDRESS=academy.academy.com:12052
      - CORE_PEER_CAHINCODELISTENADDRESS=0.0.0.0:12052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=academy.academy.com:12051
      - CORE_PEER_GOSSIP_BOOTSTRAP=app.hiring.com:10051
      - CORE_PEER_LICALMSPID=hiring
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=hiringcouchdb.hiring.com:5984
      # The CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME and CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD
      # provide the credentials for ledger to connect to CouchDB.  The username and password must
      # match the username and password set for the associated CouchDB.
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=hiringcouchdb.hiring.com
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=hiringcouchdb
    tty: true
    ports:
      - 12051:12051
      - 12052:12052
    volumes:
       - ./hiring/hiring/:/fabric/
       - ./hiring/hiring/config/:/config/
    depends_on:
      - orderer.ca.com
      - hiringcouchdb.hiring.com
    networks:
      - pheromone

  hiringcouchdb.hiring.com:
    container_name: hiringcouchdb.hiring.com
    image: hyperledger/fabric-couchdb
    # Populate the COUCHDB_USER and COUCHDB_PASSWORD to set an admin user and password
    # for CouchDB.  This will prevent CouchDB from operating in an "Admin Party" mode.
    environment:
      - COUCHDB_USER=hiringcouchdb.hiring.com
      - COUCHDB_PASSWORD=hiringcouchdb
    ports:
      - 11984:5984
    networks:
      - pheromone 

  academy.academy.com:
    container_name: academy.academy.com
    image: nawhes/fabric-peer:1
    environment: 
      - GODEBUG=netdns=go 
      - CORE_PEER_ID=academy.academy.com
      - CORE_PEER_ADDRESS=academy.academy.com:13051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:13051
      - CORE_PEER_CHAINCODEADDRESS=academy.academy.com:13052
      - CORE_PEER_CAHINCODELISTENADDRESS=0.0.0.0:13052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=academy.academy.com:13051
      - CORE_PEER_GOSSIP_BOOTSTRAP=app.app.com:7051
      - CORE_PEER_LICALMSPID=academy
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=academycouchdb.academy.com:5984
      # The CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME and CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD
      # provide the credentials for ledger to connect to CouchDB.  The username and password must
      # match the username and password set for the associated CouchDB.
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=academycouchdb.hiring.com
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=academycouchdb
    tty: true
    ports:
      - 13051:13051
      - 13052:13052
    volumes:
        - ./academy/academy/:/fabric/
        - ./academy/academy/config/:/config/
    depends_on:
      - orderer.ca.com
      - academycouchdb.academy.com
    networks:
      - pheromone

  academycouchdb.academy.com:
    container_name: academycouchdb.academy.com
    image: hyperledger/fabric-couchdb
    # Populate the COUCHDB_USER and COUCHDB_PASSWORD to set an admin user and password
    # for CouchDB.  This will prevent CouchDB from operating in an "Admin Party" mode.
    environment:
      - COUCHDB_USER=academycouchdb.academy.com
      - COUCHDB_PASSWORD=academycouchdb
    ports:
      - 12984:5984
    networks:
      - pheromone 
